# Introduction
Say you want a better form of a list that can easily change the numbers of the list all at once. Then Arrays are just your thing

# Creating an Array
To create an array, you have to first import numpy. 

In [1]:
import numpy as np

Then, you want to create an array and use a list as the argument. For this example, I'm going to use a list of random numbers.

In [3]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


Looks just like a normal list. However, now it can do many functions that lists cannot do.

# Functions of Arrays
Arrays are not like lists. If they are added together or multiplied by a number, the results are different
## Adding Arrays together
When adding lists together, you concotenate them. However, when you add arrays together, the size of the resulting array stays the same with the indexes the sum of the elements at that index. So basically, if we add arrays x and y together, the result[0] will be x[0] + y[0]

In [4]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y)

[5 7 9]


## Multiplying or Diviging Arrays By a Constant
When multiplying lists by a number, they just multiplies the list. Division isn't even allowed in lists. However, when you multiple OR divide an array with a constant, the expression applies to each element in the array:

In [5]:
print(x*3)

[3 6 9]


# Accessing Subsets of Arrays
Similar to lists, you only need to call the index using square brackets:

In [6]:
print(x[1])

2


Say you want specific rows that fullfills something. Then, you can put a conditional statement into the index of the array:

In [16]:
xcond = x < 2
print(xcond)

[ True False False]


Then, you could use that boolean array to print only the rows you desire:

In [17]:
print(x[xcond])

[1]


# Functions of Arrays
There are also some statistical functions for arrays: mean, medium, and std. Each method is called from numpy and has an argument of a 1D array:

In [14]:
print(x)
print(np.mean(x))
print(np.median(x))
print(np.std(x))

[1 2 3]
2.0
2.0
0.816496580928


# How to Create 2D Arrays
So lets say you wanna create an array that contains more than one row. To do this, we use a list of lists when creating the array:

In [7]:
z = [[1,2],[3,4],[5,6]]
twoD = np.array(z)
print(twoD)

[[1 2]
 [3 4]
 [5 6]]


# Subsetting a 2D Array
Subsetting a 2D Array is a lot more easier than lists. Simply use square brackets and indicate the rows and columns you desire:

In [9]:
print(twoD[:,1])

[2 4 6]


# 2D Arithmetic
The arithmetic for 2D arrays is very similar to 1D arrays. Multiplying the array multiplies every element while adding two arrays creates an array that contains the sums of the elements. However, when we add an array of 1 x 2, it adds the values to each row:

In [13]:
print(z)
print()
print(z + np.array([10,10]))

[[1, 2], [3, 4], [5, 6]]

[[11 12]
 [13 14]
 [15 16]]


# Summary
Arrays are used if you want to combine data sets or change each element by the same operator. They have functions to help calculate statistical data. Lastly, they can even be 2D!